### ISSUE TITLE
Great job!

### ISSUE THREAD

**Issue by mimran980** [YingWANGG/M2IB#1]
I am trying to use your model on another dataset, however, I am confused where to start. Can you provide some details on how to train this code on a new dataset?

**Comment by YingWANGG** [comment]
Thank you for your interest in our paper! For a quick start, you could try the colab where you can upload example images and texts from your dataset and play with the hyperparameters. For hyperparameter tuning, I plan to release the code within the next two weeks.

**Comment by mimran980** [comment]
Could you please provide code for how to start training? I cannot see main class or how to run training.

**Comment by YingWANGG** [comment]
To clarify, M2IB is an attribution method used to interpret a trained VLM. If you are referring to how to train the information bottleneck, you may want to look at the `_train_bottleneck` function inside `iba.py`. 

To generate the saliency maps on image and text, you can use the code in the colab as an example.

**Comment by mimran980** [comment]
Thank you Ying! yes I was referring to the added IBA layer. I want to train the model on the conceptual captions dataset. If you have code for the dataset preprocessing and training and validation loops that would be great if you can share with it @ miknust08@gmail.com. Thanks again!

**Comment by YingWANGG** [comment]
In this paper, we adopt a per-sample bottleneck (i.e. we train the IBA layer for each sample independently), so there is no validation stage. To generate saliency maps for each image-text pair in Conceptual Captions, you can directly use the code [here](https://colab.research.google.com/drive/1TeRDHYg4AXbQf0XqUcgC-3sH0fJe4Tia?usp=sharing) where the preprocessing step is encapsulated.
